/**
 * oszNamen — die Oszillator-Listen (Anzeige „Sample 001 …") zweier Firmwares,
 * erzeugt von scripts/make-osz-namen.mjs aus den SYSTEM.VSB-Dateien
 * (Tabelle bei Datei 0xD9BB0, 32 Bytes je Platz). Index = Anzeige − 1.
 *
 *   - HACKTRIBE: 274 Plaetze, Hacktribes Reihenfolge (FM 35–142, VPM 143–274).
 *   - TEKKFORGE: 362 Plaetze, die ALLES2-Firmware — FM je Programm −24…+24
 *     (35–230), VPM 231–362.
 *
 * Der Editor bietet sie in der Part-Auswahl unter „Oszillatoren" an; welche
 * Liste gilt, entscheidet die Einstellung „Oszillator-Liste" (Standard
 * TekkForge, weil das Geraet des Nutzers diese Firmware traegt).
 */
export type OszNameEintrag = readonly [name: string, kategorie: string];

export const OSZ_NAMEN_HACKTRIBE: readonly OszNameEintrag[] = [
  ["SAW", "Analog"],
  ["PULSE", "Analog"],
  ["TRIANGLE", "Analog"],
  ["SINE", "Analog"],
  ["UNI-SAW", "Analog"],
  ["UNI-SQU", "Analog"],
  ["UNI-TRI", "Analog"],
  ["UNI-SINE", "Analog"],
  ["SYNC-SAW", "Analog"],
  ["SYNC-SQU", "Analog"],
  ["SYNC-TRI", "Analog"],
  ["SYNC-SINE", "Analog"],
  ["HPF NOISE", "Analog"],
  ["LPF NOISE", "Analog"],
  ["LOFI NOISE", "Analog"],
  ["REZ NOISE", "Analog"],
  ["Audio In Mn", "Audio In"],
  ["Audio In St", "Audio In"],
  ["DUAL-SAW", "Analog"],
  ["DUAL-SQU", "Analog"],
  ["DUAL-TRI", "Analog"],
  ["DUAL-SINE", "Analog"],
  ["OCT-SAW", "Analog"],
  ["OCT-SQU", "Analog"],
  ["OCT-TRI", "Analog"],
  ["OCT-SINE", "Analog"],
  ["CHIP-TRI 1", "Analog"],
  ["CHIP-TRI 2", "Analog"],
  ["CHIP-PULSE", "Analog"],
  ["CHIP-NOISE", "Analog"],
  ["RING-SAW", "Analog"],
  ["RING-SQU", "Analog"],
  ["RING-TRI", "Analog"],
  ["RING-SINE", "Analog"],
  ["X-SAW -24", "FM"],
  ["X-SAW -20", "FM"],
  ["X-SAW -16", "FM"],
  ["X-SAW -12", "FM"],
  ["X-SAW -11", "FM"],
  ["X-SAW -10", "FM"],
  ["X-SAW -9", "FM"],
  ["X-SAW -8", "FM"],
  ["X-SAW -7", "FM"],
  ["X-SAW -6", "FM"],
  ["X-SAW -5", "FM"],
  ["X-SAW -2", "FM"],
  ["X-SAW -1", "FM"],
  ["X-SAW 0", "FM"],
  ["X-SAW +1", "FM"],
  ["X-SAW +2", "FM"],
  ["X-SAW +5", "FM"],
  ["X-SAW +6", "FM"],
  ["X-SAW +7", "FM"],
  ["X-SAW +8", "FM"],
  ["X-SAW +9", "FM"],
  ["X-SAW +10", "FM"],
  ["X-SAW +11", "FM"],
  ["X-SAW +12", "FM"],
  ["X-SAW +16", "FM"],
  ["X-SAW +20", "FM"],
  ["X-SAW +24", "FM"],
  ["X-SQUARE -24", "FM"],
  ["X-SQUARE -20", "FM"],
  ["X-SQUARE -16", "FM"],
  ["X-SQUARE -12", "FM"],
  ["X-SQUARE -11", "FM"],
  ["X-SQUARE -10", "FM"],
  ["X-SQUARE -9", "FM"],
  ["X-SQUARE -8", "FM"],
  ["X-SQUARE -7", "FM"],
  ["X-SQUARE -6", "FM"],
  ["X-SQUARE -5", "FM"],
  ["X-SQUARE -2", "FM"],
  ["X-SQUARE -1", "FM"],
  ["X-SQUARE 0", "FM"],
  ["X-SQUARE +1", "FM"],
  ["X-SQUARE +2", "FM"],
  ["X-SQUARE +5", "FM"],
  ["X-SQUARE +6", "FM"],
  ["X-SQUARE +7", "FM"],
  ["X-SQUARE +8", "FM"],
  ["X-SQUARE +9", "FM"],
  ["X-SQUARE +10", "FM"],
  ["X-SQUARE +11", "FM"],
  ["X-SQUARE +12", "FM"],
  ["X-SQUARE +16", "FM"],
  ["X-SQUARE +20", "FM"],
  ["X-SQUARE +24", "FM"],
  ["X-TRI -24", "FM"],
  ["X-TRI -20", "FM"],
  ["X-TRI -16", "FM"],
  ["X-TRI -12", "FM"],
  ["X-TRI -11", "FM"],
  ["X-TRI -10", "FM"],
  ["X-TRI -9", "FM"],
  ["X-TRI -8", "FM"],
  ["X-TRI -7", "FM"],
  ["X-TRI -6", "FM"],
  ["X-TRI -5", "FM"],
  ["X-TRI -2", "FM"],
  ["X-TRI -1", "FM"],
  ["X-TRI 0", "FM"],
  ["X-TRI +1", "FM"],
  ["X-TRI +2", "FM"],
  ["X-TRI +5", "FM"],
  ["X-TRI +6", "FM"],
  ["X-TRI +7", "FM"],
  ["X-TRI +8", "FM"],
  ["X-TRI +9", "FM"],
  ["X-TRI +10", "FM"],
  ["X-TRI +11", "FM"],
  ["X-TRI +12", "FM"],
  ["X-TRI +16", "FM"],
  ["X-TRI +20", "FM"],
  ["X-TRI +24", "FM"],
  ["X-SINE -24", "FM"],
  ["X-SINE -20", "FM"],
  ["X-SINE -16", "FM"],
  ["X-SINE -12", "FM"],
  ["X-SINE -11", "FM"],
  ["X-SINE -10", "FM"],
  ["X-SINE -9", "FM"],
  ["X-SINE -8", "FM"],
  ["X-SINE -7", "FM"],
  ["X-SINE -6", "FM"],
  ["X-SINE -5", "FM"],
  ["X-SINE -2", "FM"],
  ["X-SINE -1", "FM"],
  ["X-SINE 0", "FM"],
  ["X-SINE +1", "FM"],
  ["X-SINE +2", "FM"],
  ["X-SINE +5", "FM"],
  ["X-SINE +6", "FM"],
  ["X-SINE +7", "FM"],
  ["X-SINE +8", "FM"],
  ["X-SINE +9", "FM"],
  ["X-SINE +10", "FM"],
  ["X-SINE +11", "FM"],
  ["X-SINE +12", "FM"],
  ["X-SINE +16", "FM"],
  ["X-SINE +20", "FM"],
  ["X-SINE +24", "FM"],
  ["VPM-SAW 0.5", "VPM"],
  ["VPM-SAW 1", "VPM"],
  ["VPM-SAW 2", "VPM"],
  ["VPM-SAW 3", "VPM"],
  ["VPM-SAW 4", "VPM"],
  ["VPM-SAW 5", "VPM"],
  ["VPM-SAW 6", "VPM"],
  ["VPM-SAW 7", "VPM"],
  ["VPM-SAW 8", "VPM"],
  ["VPM-SAW 9", "VPM"],
  ["VPM-SAW 10", "VPM"],
  ["VPM-SAW 11", "VPM"],
  ["VPM-SAW 12", "VPM"],
  ["VPM-SAW 13", "VPM"],
  ["VPM-SAW 14", "VPM"],
  ["VPM-SAW 15", "VPM"],
  ["VPM-SAW 16", "VPM"],
  ["VPM-SAW 17", "VPM"],
  ["VPM-SAW 18", "VPM"],
  ["VPM-SAW 19", "VPM"],
  ["VPM-SAW 20", "VPM"],
  ["VPM-SAW 21", "VPM"],
  ["VPM-SAW 22", "VPM"],
  ["VPM-SAW 23", "VPM"],
  ["VPM-SAW 24", "VPM"],
  ["VPM-SAW 25", "VPM"],
  ["VPM-SAW 26", "VPM"],
  ["VPM-SAW 27", "VPM"],
  ["VPM-SAW 28", "VPM"],
  ["VPM-SAW 29", "VPM"],
  ["VPM-SAW 30", "VPM"],
  ["VPM-SAW 31", "VPM"],
  ["VPM-SAW 32", "VPM"],
  ["VPM-SQUARE 0.5", "VPM"],
  ["VPM-SQUARE 1", "VPM"],
  ["VPM-SQUARE 2", "VPM"],
  ["VPM-SQUARE 3", "VPM"],
  ["VPM-SQUARE 4", "VPM"],
  ["VPM-SQUARE 5", "VPM"],
  ["VPM-SQUARE 6", "VPM"],
  ["VPM-SQUARE 7", "VPM"],
  ["VPM-SQUARE 8", "VPM"],
  ["VPM-SQUARE 9", "VPM"],
  ["VPM-SQUARE 10", "VPM"],
  ["VPM-SQUARE 11", "VPM"],
  ["VPM-SQUARE 12", "VPM"],
  ["VPM-SQUARE 13", "VPM"],
  ["VPM-SQUARE 14", "VPM"],
  ["VPM-SQUARE 15", "VPM"],
  ["VPM-SQUARE 16", "VPM"],
  ["VPM-SQUARE 17", "VPM"],
  ["VPM-SQUARE 18", "VPM"],
  ["VPM-SQUARE 19", "VPM"],
  ["VPM-SQUARE 20", "VPM"],
  ["VPM-SQUARE 21", "VPM"],
  ["VPM-SQUARE 22", "VPM"],
  ["VPM-SQUARE 23", "VPM"],
  ["VPM-SQUARE 24", "VPM"],
  ["VPM-SQUARE 25", "VPM"],
  ["VPM-SQUARE 26", "VPM"],
  ["VPM-SQUARE 27", "VPM"],
  ["VPM-SQUARE 28", "VPM"],
  ["VPM-SQUARE 29", "VPM"],
  ["VPM-SQUARE 30", "VPM"],
  ["VPM-SQUARE 31", "VPM"],
  ["VPM-SQUARE 32", "VPM"],
  ["VPM-TRI 0.5", "VPM"],
  ["VPM-TRI 1", "VPM"],
  ["VPM-TRI 2", "VPM"],
  ["VPM-TRI 3", "VPM"],
  ["VPM-TRI 4", "VPM"],
  ["VPM-TRI 5", "VPM"],
  ["VPM-TRI 6", "VPM"],
  ["VPM-TRI 7", "VPM"],
  ["VPM-TRI 8", "VPM"],
  ["VPM-TRI 9", "VPM"],
  ["VPM-TRI 10", "VPM"],
  ["VPM-TRI 11", "VPM"],
  ["VPM-TRI 12", "VPM"],
  ["VPM-TRI 13", "VPM"],
  ["VPM-TRI 14", "VPM"],
  ["VPM-TRI 15", "VPM"],
  ["VPM-TRI 16", "VPM"],
  ["VPM-TRI 17", "VPM"],
  ["VPM-TRI 18", "VPM"],
  ["VPM-TRI 19", "VPM"],
  ["VPM-TRI 20", "VPM"],
  ["VPM-TRI 21", "VPM"],
  ["VPM-TRI 22", "VPM"],
  ["VPM-TRI 23", "VPM"],
  ["VPM-TRI 24", "VPM"],
  ["VPM-TRI 25", "VPM"],
  ["VPM-TRI 26", "VPM"],
  ["VPM-TRI 27", "VPM"],
  ["VPM-TRI 28", "VPM"],
  ["VPM-TRI 29", "VPM"],
  ["VPM-TRI 30", "VPM"],
  ["VPM-TRI 31", "VPM"],
  ["VPM-TRI 32", "VPM"],
  ["VPM-SINE 0.5", "VPM"],
  ["VPM-SINE 1", "VPM"],
  ["VPM-SINE 2", "VPM"],
  ["VPM-SINE 3", "VPM"],
  ["VPM-SINE 4", "VPM"],
  ["VPM-SINE 5", "VPM"],
  ["VPM-SINE 6", "VPM"],
  ["VPM-SINE 7", "VPM"],
  ["VPM-SINE 8", "VPM"],
  ["VPM-SINE 9", "VPM"],
  ["VPM-SINE 10", "VPM"],
  ["VPM-SINE 11", "VPM"],
  ["VPM-SINE 12", "VPM"],
  ["VPM-SINE 13", "VPM"],
  ["VPM-SINE 14", "VPM"],
  ["VPM-SINE 15", "VPM"],
  ["VPM-SINE 16", "VPM"],
  ["VPM-SINE 17", "VPM"],
  ["VPM-SINE 18", "VPM"],
  ["VPM-SINE 19", "VPM"],
  ["VPM-SINE 20", "VPM"],
  ["VPM-SINE 21", "VPM"],
  ["VPM-SINE 22", "VPM"],
  ["VPM-SINE 23", "VPM"],
  ["VPM-SINE 24", "VPM"],
  ["VPM-SINE 25", "VPM"],
  ["VPM-SINE 26", "VPM"],
  ["VPM-SINE 27", "VPM"],
  ["VPM-SINE 28", "VPM"],
  ["VPM-SINE 29", "VPM"],
  ["VPM-SINE 30", "VPM"],
  ["VPM-SINE 31", "VPM"],
  ["VPM-SINE 32", "VPM"],
];

export const OSZ_NAMEN_TEKKFORGE: readonly OszNameEintrag[] = [
  ["SAW", "Analog"],
  ["PULSE", "Analog"],
  ["TRIANGLE", "Analog"],
  ["SINE", "Analog"],
  ["UNI-SAW", "Analog"],
  ["UNI-SQU", "Analog"],
  ["UNI-TRI", "Analog"],
  ["UNI-SINE", "Analog"],
  ["SYNC-SAW", "Analog"],
  ["SYNC-SQU", "Analog"],
  ["SYNC-TRI", "Analog"],
  ["SYNC-SINE", "Analog"],
  ["HPF NOISE", "Analog"],
  ["LPF NOISE", "Analog"],
  ["LOFI NOISE", "Analog"],
  ["REZ NOISE", "Analog"],
  ["Audio In Mn", "Audio In"],
  ["Audio In St", "Audio In"],
  ["DUAL-SAW", "Analog"],
  ["DUAL-SQU", "Analog"],
  ["DUAL-TRI", "Analog"],
  ["DUAL-SINE", "Analog"],
  ["OCT-SAW", "Analog"],
  ["OCT-SQU", "Analog"],
  ["OCT-TRI", "Analog"],
  ["OCT-SINE", "Analog"],
  ["CHIP-TRI 1", "Analog"],
  ["CHIP-TRI 2", "Analog"],
  ["CHIP-PULSE", "Analog"],
  ["CHIP-NOISE", "Analog"],
  ["RING-SAW", "Analog"],
  ["RING-SQU", "Analog"],
  ["RING-TRI", "Analog"],
  ["RING-SINE", "Analog"],
  ["X-SAW -24", "FM"],
  ["X-SAW -23", "FM"],
  ["X-SAW -22", "FM"],
  ["X-SAW -21", "FM"],
  ["X-SAW -20", "FM"],
  ["X-SAW -19", "FM"],
  ["X-SAW -18", "FM"],
  ["X-SAW -17", "FM"],
  ["X-SAW -16", "FM"],
  ["X-SAW -15", "FM"],
  ["X-SAW -14", "FM"],
  ["X-SAW -13", "FM"],
  ["X-SAW -12", "FM"],
  ["X-SAW -11", "FM"],
  ["X-SAW -10", "FM"],
  ["X-SAW -9", "FM"],
  ["X-SAW -8", "FM"],
  ["X-SAW -7", "FM"],
  ["X-SAW -6", "FM"],
  ["X-SAW -5", "FM"],
  ["X-SAW -4", "FM"],
  ["X-SAW -3", "FM"],
  ["X-SAW -2", "FM"],
  ["X-SAW -1", "FM"],
  ["X-SAW 0", "FM"],
  ["X-SAW +1", "FM"],
  ["X-SAW +2", "FM"],
  ["X-SAW +3", "FM"],
  ["X-SAW +4", "FM"],
  ["X-SAW +5", "FM"],
  ["X-SAW +6", "FM"],
  ["X-SAW +7", "FM"],
  ["X-SAW +8", "FM"],
  ["X-SAW +9", "FM"],
  ["X-SAW +10", "FM"],
  ["X-SAW +11", "FM"],
  ["X-SAW +12", "FM"],
  ["X-SAW +13", "FM"],
  ["X-SAW +14", "FM"],
  ["X-SAW +15", "FM"],
  ["X-SAW +16", "FM"],
  ["X-SAW +17", "FM"],
  ["X-SAW +18", "FM"],
  ["X-SAW +19", "FM"],
  ["X-SAW +20", "FM"],
  ["X-SAW +21", "FM"],
  ["X-SAW +22", "FM"],
  ["X-SAW +23", "FM"],
  ["X-SAW +24", "FM"],
  ["X-SQUARE -24", "FM"],
  ["X-SQUARE -23", "FM"],
  ["X-SQUARE -22", "FM"],
  ["X-SQUARE -21", "FM"],
  ["X-SQUARE -20", "FM"],
  ["X-SQUARE -19", "FM"],
  ["X-SQUARE -18", "FM"],
  ["X-SQUARE -17", "FM"],
  ["X-SQUARE -16", "FM"],
  ["X-SQUARE -15", "FM"],
  ["X-SQUARE -14", "FM"],
  ["X-SQUARE -13", "FM"],
  ["X-SQUARE -12", "FM"],
  ["X-SQUARE -11", "FM"],
  ["X-SQUARE -10", "FM"],
  ["X-SQUARE -9", "FM"],
  ["X-SQUARE -8", "FM"],
  ["X-SQUARE -7", "FM"],
  ["X-SQUARE -6", "FM"],
  ["X-SQUARE -5", "FM"],
  ["X-SQUARE -4", "FM"],
  ["X-SQUARE -3", "FM"],
  ["X-SQUARE -2", "FM"],
  ["X-SQUARE -1", "FM"],
  ["X-SQUARE 0", "FM"],
  ["X-SQUARE +1", "FM"],
  ["X-SQUARE +2", "FM"],
  ["X-SQUARE +3", "FM"],
  ["X-SQUARE +4", "FM"],
  ["X-SQUARE +5", "FM"],
  ["X-SQUARE +6", "FM"],
  ["X-SQUARE +7", "FM"],
  ["X-SQUARE +8", "FM"],
  ["X-SQUARE +9", "FM"],
  ["X-SQUARE +10", "FM"],
  ["X-SQUARE +11", "FM"],
  ["X-SQUARE +12", "FM"],
  ["X-SQUARE +13", "FM"],
  ["X-SQUARE +14", "FM"],
  ["X-SQUARE +15", "FM"],
  ["X-SQUARE +16", "FM"],
  ["X-SQUARE +17", "FM"],
  ["X-SQUARE +18", "FM"],
  ["X-SQUARE +19", "FM"],
  ["X-SQUARE +20", "FM"],
  ["X-SQUARE +21", "FM"],
  ["X-SQUARE +22", "FM"],
  ["X-SQUARE +23", "FM"],
  ["X-SQUARE +24", "FM"],
  ["X-TRI -24", "FM"],
  ["X-TRI -23", "FM"],
  ["X-TRI -22", "FM"],
  ["X-TRI -21", "FM"],
  ["X-TRI -20", "FM"],
  ["X-TRI -19", "FM"],
  ["X-TRI -18", "FM"],
  ["X-TRI -17", "FM"],
  ["X-TRI -16", "FM"],
  ["X-TRI -15", "FM"],
  ["X-TRI -14", "FM"],
  ["X-TRI -13", "FM"],
  ["X-TRI -12", "FM"],
  ["X-TRI -11", "FM"],
  ["X-TRI -10", "FM"],
  ["X-TRI -9", "FM"],
  ["X-TRI -8", "FM"],
  ["X-TRI -7", "FM"],
  ["X-TRI -6", "FM"],
  ["X-TRI -5", "FM"],
  ["X-TRI -4", "FM"],
  ["X-TRI -3", "FM"],
  ["X-TRI -2", "FM"],
  ["X-TRI -1", "FM"],
  ["X-TRI 0", "FM"],
  ["X-TRI +1", "FM"],
  ["X-TRI +2", "FM"],
  ["X-TRI +3", "FM"],
  ["X-TRI +4", "FM"],
  ["X-TRI +5", "FM"],
  ["X-TRI +6", "FM"],
  ["X-TRI +7", "FM"],
  ["X-TRI +8", "FM"],
  ["X-TRI +9", "FM"],
  ["X-TRI +10", "FM"],
  ["X-TRI +11", "FM"],
  ["X-TRI +12", "FM"],
  ["X-TRI +13", "FM"],
  ["X-TRI +14", "FM"],
  ["X-TRI +15", "FM"],
  ["X-TRI +16", "FM"],
  ["X-TRI +17", "FM"],
  ["X-TRI +18", "FM"],
  ["X-TRI +19", "FM"],
  ["X-TRI +20", "FM"],
  ["X-TRI +21", "FM"],
  ["X-TRI +22", "FM"],
  ["X-TRI +23", "FM"],
  ["X-TRI +24", "FM"],
  ["X-SINE -24", "FM"],
  ["X-SINE -23", "FM"],
  ["X-SINE -22", "FM"],
  ["X-SINE -21", "FM"],
  ["X-SINE -20", "FM"],
  ["X-SINE -19", "FM"],
  ["X-SINE -18", "FM"],
  ["X-SINE -17", "FM"],
  ["X-SINE -16", "FM"],
  ["X-SINE -15", "FM"],
  ["X-SINE -14", "FM"],
  ["X-SINE -13", "FM"],
  ["X-SINE -12", "FM"],
  ["X-SINE -11", "FM"],
  ["X-SINE -10", "FM"],
  ["X-SINE -9", "FM"],
  ["X-SINE -8", "FM"],
  ["X-SINE -7", "FM"],
  ["X-SINE -6", "FM"],
  ["X-SINE -5", "FM"],
  ["X-SINE -4", "FM"],
  ["X-SINE -3", "FM"],
  ["X-SINE -2", "FM"],
  ["X-SINE -1", "FM"],
  ["X-SINE 0", "FM"],
  ["X-SINE +1", "FM"],
  ["X-SINE +2", "FM"],
  ["X-SINE +3", "FM"],
  ["X-SINE +4", "FM"],
  ["X-SINE +5", "FM"],
  ["X-SINE +6", "FM"],
  ["X-SINE +7", "FM"],
  ["X-SINE +8", "FM"],
  ["X-SINE +9", "FM"],
  ["X-SINE +10", "FM"],
  ["X-SINE +11", "FM"],
  ["X-SINE +12", "FM"],
  ["X-SINE +13", "FM"],
  ["X-SINE +14", "FM"],
  ["X-SINE +15", "FM"],
  ["X-SINE +16", "FM"],
  ["X-SINE +17", "FM"],
  ["X-SINE +18", "FM"],
  ["X-SINE +19", "FM"],
  ["X-SINE +20", "FM"],
  ["X-SINE +21", "FM"],
  ["X-SINE +22", "FM"],
  ["X-SINE +23", "FM"],
  ["X-SINE +24", "FM"],
  ["VPM-SAW 0.5", "VPM"],
  ["VPM-SAW 1", "VPM"],
  ["VPM-SAW 2", "VPM"],
  ["VPM-SAW 3", "VPM"],
  ["VPM-SAW 4", "VPM"],
  ["VPM-SAW 5", "VPM"],
  ["VPM-SAW 6", "VPM"],
  ["VPM-SAW 7", "VPM"],
  ["VPM-SAW 8", "VPM"],
  ["VPM-SAW 9", "VPM"],
  ["VPM-SAW 10", "VPM"],
  ["VPM-SAW 11", "VPM"],
  ["VPM-SAW 12", "VPM"],
  ["VPM-SAW 13", "VPM"],
  ["VPM-SAW 14", "VPM"],
  ["VPM-SAW 15", "VPM"],
  ["VPM-SAW 16", "VPM"],
  ["VPM-SAW 17", "VPM"],
  ["VPM-SAW 18", "VPM"],
  ["VPM-SAW 19", "VPM"],
  ["VPM-SAW 20", "VPM"],
  ["VPM-SAW 21", "VPM"],
  ["VPM-SAW 22", "VPM"],
  ["VPM-SAW 23", "VPM"],
  ["VPM-SAW 24", "VPM"],
  ["VPM-SAW 25", "VPM"],
  ["VPM-SAW 26", "VPM"],
  ["VPM-SAW 27", "VPM"],
  ["VPM-SAW 28", "VPM"],
  ["VPM-SAW 29", "VPM"],
  ["VPM-SAW 30", "VPM"],
  ["VPM-SAW 31", "VPM"],
  ["VPM-SAW 32", "VPM"],
  ["VPM-SQUARE 0.5", "VPM"],
  ["VPM-SQUARE 1", "VPM"],
  ["VPM-SQUARE 2", "VPM"],
  ["VPM-SQUARE 3", "VPM"],
  ["VPM-SQUARE 4", "VPM"],
  ["VPM-SQUARE 5", "VPM"],
  ["VPM-SQUARE 6", "VPM"],
  ["VPM-SQUARE 7", "VPM"],
  ["VPM-SQUARE 8", "VPM"],
  ["VPM-SQUARE 9", "VPM"],
  ["VPM-SQUARE 10", "VPM"],
  ["VPM-SQUARE 11", "VPM"],
  ["VPM-SQUARE 12", "VPM"],
  ["VPM-SQUARE 13", "VPM"],
  ["VPM-SQUARE 14", "VPM"],
  ["VPM-SQUARE 15", "VPM"],
  ["VPM-SQUARE 16", "VPM"],
  ["VPM-SQUARE 17", "VPM"],
  ["VPM-SQUARE 18", "VPM"],
  ["VPM-SQUARE 19", "VPM"],
  ["VPM-SQUARE 20", "VPM"],
  ["VPM-SQUARE 21", "VPM"],
  ["VPM-SQUARE 22", "VPM"],
  ["VPM-SQUARE 23", "VPM"],
  ["VPM-SQUARE 24", "VPM"],
  ["VPM-SQUARE 25", "VPM"],
  ["VPM-SQUARE 26", "VPM"],
  ["VPM-SQUARE 27", "VPM"],
  ["VPM-SQUARE 28", "VPM"],
  ["VPM-SQUARE 29", "VPM"],
  ["VPM-SQUARE 30", "VPM"],
  ["VPM-SQUARE 31", "VPM"],
  ["VPM-SQUARE 32", "VPM"],
  ["VPM-TRI 0.5", "VPM"],
  ["VPM-TRI 1", "VPM"],
  ["VPM-TRI 2", "VPM"],
  ["VPM-TRI 3", "VPM"],
  ["VPM-TRI 4", "VPM"],
  ["VPM-TRI 5", "VPM"],
  ["VPM-TRI 6", "VPM"],
  ["VPM-TRI 7", "VPM"],
  ["VPM-TRI 8", "VPM"],
  ["VPM-TRI 9", "VPM"],
  ["VPM-TRI 10", "VPM"],
  ["VPM-TRI 11", "VPM"],
  ["VPM-TRI 12", "VPM"],
  ["VPM-TRI 13", "VPM"],
  ["VPM-TRI 14", "VPM"],
  ["VPM-TRI 15", "VPM"],
  ["VPM-TRI 16", "VPM"],
  ["VPM-TRI 17", "VPM"],
  ["VPM-TRI 18", "VPM"],
  ["VPM-TRI 19", "VPM"],
  ["VPM-TRI 20", "VPM"],
  ["VPM-TRI 21", "VPM"],
  ["VPM-TRI 22", "VPM"],
  ["VPM-TRI 23", "VPM"],
  ["VPM-TRI 24", "VPM"],
  ["VPM-TRI 25", "VPM"],
  ["VPM-TRI 26", "VPM"],
  ["VPM-TRI 27", "VPM"],
  ["VPM-TRI 28", "VPM"],
  ["VPM-TRI 29", "VPM"],
  ["VPM-TRI 30", "VPM"],
  ["VPM-TRI 31", "VPM"],
  ["VPM-TRI 32", "VPM"],
  ["VPM-SINE 0.5", "VPM"],
  ["VPM-SINE 1", "VPM"],
  ["VPM-SINE 2", "VPM"],
  ["VPM-SINE 3", "VPM"],
  ["VPM-SINE 4", "VPM"],
  ["VPM-SINE 5", "VPM"],
  ["VPM-SINE 6", "VPM"],
  ["VPM-SINE 7", "VPM"],
  ["VPM-SINE 8", "VPM"],
  ["VPM-SINE 9", "VPM"],
  ["VPM-SINE 10", "VPM"],
  ["VPM-SINE 11", "VPM"],
  ["VPM-SINE 12", "VPM"],
  ["VPM-SINE 13", "VPM"],
  ["VPM-SINE 14", "VPM"],
  ["VPM-SINE 15", "VPM"],
  ["VPM-SINE 16", "VPM"],
  ["VPM-SINE 17", "VPM"],
  ["VPM-SINE 18", "VPM"],
  ["VPM-SINE 19", "VPM"],
  ["VPM-SINE 20", "VPM"],
  ["VPM-SINE 21", "VPM"],
  ["VPM-SINE 22", "VPM"],
  ["VPM-SINE 23", "VPM"],
  ["VPM-SINE 24", "VPM"],
  ["VPM-SINE 25", "VPM"],
  ["VPM-SINE 26", "VPM"],
  ["VPM-SINE 27", "VPM"],
  ["VPM-SINE 28", "VPM"],
  ["VPM-SINE 29", "VPM"],
  ["VPM-SINE 30", "VPM"],
  ["VPM-SINE 31", "VPM"],
  ["VPM-SINE 32", "VPM"],
];

export const OSZ_LISTEN = { tekkforge: OSZ_NAMEN_TEKKFORGE, hacktribe: OSZ_NAMEN_HACKTRIBE } as const;
export type OszListe = keyof typeof OSZ_LISTEN;

/** Anzeigename eines Oszillator-Platzes (1-basiert) aus der gewaehlten Liste — „35 · X-SAW -24 (FM)“; unbekannt → nur die Nummer. */
export function oszNameFuer(nummer: number, liste: OszListe = "tekkforge"): string {
  const e = OSZ_LISTEN[liste][nummer - 1];
  return e ? `${nummer} · ${e[0]} (${e[1]})` : `${nummer}`;
}

const SCHLUESSEL = "tekkforge.oszListe";
/** Welche Liste der Editor zeigt — aus localStorage, Standard TekkForge. */
export function oszListeWahl(): OszListe {
  try {
    const v = globalThis.localStorage?.getItem(SCHLUESSEL);
    return v === "hacktribe" ? "hacktribe" : "tekkforge";
  } catch {
    return "tekkforge";
  }
}
export function oszListeSetzen(l: OszListe): void {
  try {
    globalThis.localStorage?.setItem(SCHLUESSEL, l);
  } catch {
    /* kein Speicher — dann eben Standard */
  }
}

/** Ist die Nummer ein Oszillator-Platz (unter den User-Samples ab 501)? */
export const istOszillatorNummer = (nummer: number | null | undefined): nummer is number => typeof nummer === "number" && nummer >= 1 && nummer <= 500;
